import { getPosts } from '@/lib/wp-api'
import { PageInfo, PostOverlayCard } from '@metablog/ui'
import type { Metadata } from 'next'
import PageBody from './PageBody'

export const metadata: Metadata = {
   title: 'Blog Page | MetaBlog',
   description: 'Generated by create next app',
}

const BlogListing = async () => {
   // ======================get posts data==========================
   const { data } = await getPosts({ per_page: 10 })

   return (
      <main>
         <div className="container mx-auto px-5 sm:px-0">
            {/* Page title info */}
            <section>
               <PageInfo
                  pageData={{
                     name: 'Latest News',
                     slug: 'blog',
                  }}
               />
            </section>

            {/* Banner */}
            <section className="my-12">
               <PostOverlayCard cardData={data[0]} />
            </section>
            <PageBody data={data} />
         </div>
      </main>
   )
}

export default BlogListing
