import React from 'react'
import type { Metadata } from 'next'
import {
   Advertisement,
   PageInfo,
   PostCard,
   PostOverlayCard,
} from '@metablog/ui'
// json data
import postsData from '@/data/posts/allPostData.json'

export const metadata: Metadata = {
   title: 'Blog Page | MetaBlog',
   description: 'Generated by create next app',
}

const BlogListing = () => {
   return (
      <main>
         <div className="container mx-auto px-5 sm:px-0">
            {/* Page title info */}
            <section>
               <PageInfo />
            </section>

            {/* Banner */}
            <section className="my-12">
               {postsData?.slice(0, 1).map((item: any, index: number) => (
                  <PostOverlayCard cardData={item} key={index} />
               ))}
            </section>

            {/* All posts component */}
            <section className="my-20">
               <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                  {postsData?.slice(1)?.map((item: any) => (
                     <PostCard cardData={item} key={item} />
                  ))}
               </div>
               <div className="flex items-center justify-center w-full mt-8">
                  <button className="btn btn-outline btn-secondary font-work px-5">
                     Load More
                  </button>
               </div>
            </section>

            {/* Advertisement component */}
            <section className="mb-24">
               <Advertisement />
            </section>
         </div>
      </main>
   )
}

export default BlogListing
